name: Release
on: [push, repository_dispatch]

jobs:
  build:
    name: RedisTimeSeries
    runs-on: ubuntu-latest
    steps:
      - id: combo
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: davidessayan/combo-plugin
          token: ${{ secrets.GH_TOKEN }}
